{% set name = "cloudflare" %}
{% set version = "4.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cloudflare-{{ version }}.tar.gz
  sha256: 40aa718163a9b0761a815bd52a7cc18a5062a10be3177cb2d4a936770cc00826

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-fancy-pypi-readme
    - pip
  run:
    - typing_extensions >=4.10,<5
    - python >={{ python_min }}
    - httpx >=0.23.0,<1
    - pydantic >=1.9.0,<3
    - typing-extensions >=4.7,<5
    - anyio >=3.5.0,<5
    - distro >=1.7.0,<2
    - sniffio

test:
  imports:
    - cloudflare
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/cloudflare/python-cloudflare
  summary: Python wrapper for the Cloudflare v4 API
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
