{% set name = "cloudflare" %}
{% set version = "2.14.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cloudflare-{{ version }}.tar.gz
  sha256: 1de49a889288d82dc5c0f2a2a746552967b99d96063f5df3a57a703642e240b4

build:
  number: 0
  noarch: python
  entry_points:
    - cli4=cli4.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - beautifulsoup4
    - jsonlines
    - pyyaml
    - requests

test:
  imports:
    - CloudFlare
    - cli4
  commands:
    - pip check
    # works but has a non-zero return :-/
    # - cli4 --version
  requires:
    - pip

about:
  home: https://github.com/cloudflare/python-cloudflare
  summary: Python wrapper for the Cloudflare v4 API
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
