{% set name = "cloudflare" %}
{% set version = "3.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cloudflare-{{ version }}.tar.gz
  sha256: 212ead08c8bd9ea1796286bb5d954d157991b3dbcab0c526332f775298ccce9f

build:
  number: 0
  noarch: python
  entry_points:
    - cli4=cli4.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - anyio >=3.5.0,<5
    - distro >=1.7.0,<2
    - httpx >=0.23.0,<1
    - pydantic >=1.9.0,<3
    - sniffio
    - typing-extensions >=4.7,<5
    - python >=3.7
    - beautifulsoup4
    - jsonlines
    - pyyaml
    - requests

test:
  imports:
    - CloudFlare
    - cli4
  commands:
    - pip check
    # works but has a non-zero return :-/
    # - cli4 --version
  requires:
    - pip

about:
  home: https://github.com/cloudflare/python-cloudflare
  summary: Python wrapper for the Cloudflare v4 API
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
